### ISSUE TITLE
如何处理不加分隔符的情况

### ISSUE THREAD

**Issue by MikuBlog** [akebe/address-parse#11]
地址紧接着名字的情况如何处理，现版本地址和名字一同被解析为详细地址

**Comment by akebe** [comment]
目前没有有效的处理方式，之前有考虑过没有匹配到名字用百家姓在`result.details`里面匹配，可是名字贴着地址的边界情况太多，很难有满意的结果

**Comment by MikuBlog** [comment]
已用jieba分词解决
