### ISSUE TITLE
直辖市辖区的识别问题

### ISSUE THREAD

**Issue by JasonYan2015** [akebe/address-parse#14]
case: 北京市市辖区东城区嘿嘿 嘿嘿 18031491271
 
市辖区会识别不出来

试了一下 

/src/parse/parse-area.js  224行

if (index > -1 && index < 3)  改成 if (index > -1 && index < 4) 就可以了
不知道这里 < 3 是出于什么考虑

**Comment by akebe** [comment]
你好，这个限定考虑的是像`福建省福州市福清市台江公寓`这种详细地址包含了地区名的边界问题，如果不加限定，要是市后面的地址包含下属区关键字，并且他比真正要匹配的区提前识别到的话，会被解析。
像我上面这个地址，如果用` if (index > -1 && index < 4) ` 就会被识别成`福建省 福州市 台区江 公寓 `
你这个问题不能直接这样简单处理，我会想个办法解决

**Comment by akebe** [comment]
`1.1.2`版本优化了`parse_area_by_city`的匹配逻辑，已经可以正常解析
