### ISSUE TITLE
广东省 东莞市 东城街道地址识别有误

### ISSUE THREAD

**Issue by ReflexFox** [akebe/address-parse#15]
"广东省 东莞市 东城街道 "这个地址识别有误，识别为"广东省 东莞市 东城区" 应该是地址数据没有更新导致的

**Comment by akebe** [comment]
好的，地址库的确很久没更新了，近期会抽空更新下

**Comment by akebe** [comment]
1.2.0已更新地址库，来源https://github.com/youzan/vant/blob/dev/src/area/demo/area.js
