### ISSUE TITLE
重庆市县城口县这个地址在1.2.0最匹配结果有误

### ISSUE THREAD

**Issue by ReflexFox** [akebe/address-parse#18]
![image](https://user-images.githubusercontent.com/42571543/86101211-85ea6280-baec-11ea-97ef-522af91a98d1.png)
第二个结果应该是最匹配的

**Comment by akebe** [comment]
感谢反馈，已在`1.2.1`版本内优化了结果排序算法，在`parseAll`启用下可获得正确结果
