### ISSUE TITLE
请教怎么加上国家部分

### ISSUE THREAD

**Issue by ajqcicon** [akebe/address-parse#22]
测试了一下，仅是识别国内的，没有国际，请教有没有什么思路没？
另外，如果这个库能通过现成的json数据来动态分析的话就更完美了

**Comment by akebe** [comment]
这个库的目的只是解析国内地址哦，不同国家地址地区规则有差异，目前也没有怎么解析其他国家地址的头绪 **主要是我也不认识😂**
