### ISSUE TITLE
山东省济宁市北湖区   无法识别到北湖区

### ISSUE THREAD

**Issue by wangliuyong** [akebe/address-parse#23]
![image](https://user-images.githubusercontent.com/36350201/90485002-8c4e9f80-e169-11ea-9378-51838374d367.png)

**Comment by akebe** [comment]
你好，查询了最新的[行政区划数据](http://www.mca.gov.cn///article/sj/xzqh/2020/2020/2020072805001.html)，并且济宁市下辖没有北湖区哦，因为这个库是根据行政区划数据解析的，如果标准数据里面没有的，就无法解析。
