### ISSUE TITLE
您好，部分地址解析错误，望更新

### ISSUE THREAD

**Issue by small-onion** [akebe/address-parse#25]
您好：
       首先特别感谢您这个项目，做一个快递的小程序。智能解析地址体验感大大提升。
但在使用过程中偶尔会遇到地址识别错误的问题，比如：“新疆伊宁市上海城徐汇苑23号楼5单元401室”。因为有“上海”和“徐汇”这两个关键字的原因会识别成： 上海  上海市  徐汇区  苑23号楼5单元401室

第二个问题是“重庆有些”县“识别不出来。用您提供的Utils.getTargetAreaListByCode查询出来，看到县是单独列出来的。不知道什么意思，还是我不会用吗？

第三个，对于某些省、自治区有：“省直辖县”、“自治区直辖县级行政区划”。这类情况每个平台称呼不一样，有的是“省直辖县”、“自治区直辖县级行政区划”，有的是：市、县都写的一样的（县级）。有的用的“其它”。能不能给个参数让用户自己选择使用哪一种替代。

再次感谢您无偿分享的精神，向您学习和致敬

**Comment by akebe** [comment]
感谢反馈，所提地址解析不准的问题已经在`1.2.6`版本修复，这是这个库目前所用解析方案的一个弊端引起，**遍历地区树，命中可信结果后直接跳出循环**，但这个**可信**只是相对而言，容易因为提前跳出而导致真实地区未经解析造成错误，但如果每次解析都全部遍历一遍，那效率太低了，只能通过大家反馈修复边界问题达到改善。
目前的解决方案是针对解析出来的前半截被当作`name`字段的内容如果包含省份名称，就进行二次解析进行修复，这样有留下一个后遗症，就是`新疆伊宁市上海城徐汇苑`可以解析，但是`伊宁市上海城徐汇苑`就解析不了，设想过如果用`city_list`去遍历可能造成新的边界问题，像`伊宁上海城徐汇`，到底是`上海市徐汇区叫伊宁的`，还是`新疆伊宁市上海城徐汇`呢，所以这个问题只能修复到这个地步了。
2.关于重庆县的那个问题，这个库的地区列表来自[vant area.js](https://github.com/youzan/vant/blob/dev/src/area/demo/area.js)，在这个数据源中重庆下辖是`5001xx`的`重庆市`和`5002xx`的`县`构成的，所以解析出来也是这个结构。这次更新优化了排序算法，现在`重庆忠县`已经能正确的把`500233`结果靠前了。

3.这个问题之前考虑过，这段时间会抽空完善配置的问题，在下个版本`v1.3.x`将允许传入自定义`area`数据，应该能解决你的问题

**Comment by small-onion** [comment]
1、所以现在的情况是只能根据反馈针对性的优化是吗？那我这边有很多识别不准确的，需要我遇到不能识别的情况，分阶段性的全部反馈吗？
比如：“湖北神农架太阳村10组” 现在就识别不出来。因为“神农架”是全称是“神农架林区”，所以必须要写“神农架林区”才能识别，写“神农架”就不行。但实际情况中很少有能写完整。 
又比如： 很多城市有四川路、南京路、北京路之类的情况。
2、重庆县级行政区的问题。1.2.6版本还是识别不了“重庆忠县忠州镇梅湾村13组”。是我没搞对吗？
3、您说会在后续版本中允许传入自定义area。但我是说的“省直辖县”、“自治区直辖县级行政区划”是在City字段中的。不知道是不是我理解错了。

再次感谢

**Comment by akebe** [comment]
1.神农架问题已在`v1.2.7`版本修复，库内生成了一个短名列表，因为`林区`这个区划名比较特殊，之前没注意到，未经特殊处理被正常清洗后的短名是`神农架林` 要导致`神农架`匹配失败，现在已修复。
正常区市不用携带区划后缀也能解析。

2.亲测可行，如果是用测试页测试的，请注意是否有浏览器缓存。

3.自定义`area`是指自定义库内的[area.js文件](https://github.com/akebe/address-parse/blob/master/src/area.js)，包含city
