### ISSUE TITLE
如果地址后面还有文字，details里面的内容不太正确

### ISSUE THREAD

**Issue by QianWu184** [akebe/address-parse#26]
我是在项目给出的测试页面直接测试的。用到的文本是 “**一段用于测试地址解析的文本，成都高新区吉泰路xxx号。后面的文本是用于结尾断字测试**”，这样测试的结果省市县是正确的，但是details里面会把详细地址后面的那些文字全部追加进去,就成了“**吉泰路xxx号 后面的文本是用于结尾断字测试**”.正确的话应该是“**吉泰路xxx号**”。请作者有空的话看看吧。最后。感谢作者分享

**Comment by akebe** [comment]
因为库的核心是提取字符串中的关键信息 `省\市\区\手机\电话\邮编`再在剩余信息中识别出`name`，为避免遗漏，余下内容都被拼接到`details`内
因为地址详情千奇百怪，`。`号在这个库中并不识别为结尾断句，也没有**结尾断句**这个概念，因为库默认认为你传入的参数就是一个未经解析的地址字符串。如果提前有确定断字可以先切割处理后再进行解析。
回到你的例子上
`成都高新区吉泰路xxx号。后面的文本是用于结尾断字测试`
`成都高新区吉泰路xxx号。XX小区XX号楼xxxx`
`成都高新区吉泰路xxx号。快递到了放在地上等我去拿`
我随手扩展了一下，你觉得在代码上是否真能完美做到判断这3个例子哪些是无效内容呢？做不到哇

**Comment by QianWu184** [comment]
> 因为库的核心是提取字符串中的关键信息 `省\市\区\手机\电话\邮编`再在剩余信息中识别出`name`，为避免遗漏，余下内容都被拼接到`details`内
> 因为地址详情千奇百怪，`。`号在这个库中并不识别为结尾断字，也没有**结尾断字**这个概念，因为库默认认为你传入的参数就是一个未经解析的地址字符串。如果提前有确定断字可以先切割处理后再进行解析。
> 回到你的例子上
> `成都高新区吉泰路xxx号。后面的文本是用于结尾断字测试`
> `成都高新区吉泰路xxx号。XX小区XX号楼xxxx`
> `成都高新区吉泰路xxx号。快递到了放在地上等我去拿`
> 我随手扩展了一下，你觉得在代码上是否真能完美做到判断这3个例子哪些是无效内容呢？做不到哇

确实是 我也是因为这个在头疼。还是感谢你的解答
