### ISSUE TITLE
未能正确识别的地址

### ISSUE THREAD

**Issue by sayeui** [akebe/address-parse#28]
这个可以正确识别：北京市朝阳区富康路姚家园3楼马云15000000000
这个不行，无法解析到name：广西南宁良庆区五象航洋城38楼马云15000000000

**Comment by akebe** [comment]
因为边界问题太多，处理起来十分复杂所以没做处理。
用你地址举个例子：
`北京市朝阳区富康路姚家园3楼马云15000000000`
`北京市朝阳区富康路姚家园楼丽丽15000000000`
我们用肉眼可以很快识别出第一个地址`name`是`马云`，第二个地址`name`是`楼丽丽`
但是从代码层面上想区分这2者是极其困难的。
因为解析结果很难尽如人意，所以这种名字跟地址完全衔接在一起没有分隔符的地址，库直接没有进行`name`解析。
