### ISSUE TITLE
手机号识别不准确导致电话和详细地址错误

### ISSUE THREAD

**Issue by liuyunpeng12** [akebe/address-parse#32]
原文：
1.北京市密云区花园小区1楼三单元301
15801691123  唐娜明收
结果：
[
    {
        "province":"北京",
        "city":"北京市",
        "area":"密云区",
        "details":"花园小区1楼三单元30 3 唐娜明收",
        "name":"1.",
        "code":"110118",
        "__type":"parseByProvince",
        "__parse":true,
        "mobile":"11580169112",
        "zip_code":"",
        "phone":""
    }
]

**Comment by akebe** [comment]
感谢反馈，匹配手机号的正则不够严谨，现已优化修复，请升级到`1.2.10`
