### ISSUE TITLE
地址解析错误

### ISSUE THREAD

**Issue by avdergh** [akebe/address-parse#33]
广东省 深圳市 宝安区 西乡街道 解析这个地址时候会有错误

**Comment by akebe** [comment]
@avdergh 我这边测试解析结果是正常的，是否是你提供的地址有误？
`https://asseek.gitee.io/address-parse/?address=广东省%20深圳市%20宝安区%20西乡街道 `

**Comment by avdergh** [comment]
> @avdergh 我这边测试解析结果是正常的，是否是你提供的地址有误？
> `https://asseek.gitee.io/address-parse/?address=广东省%20深圳市%20宝安区%20西乡街道 `

抱歉，提错地方了，是要提给另一个项目的
