### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by Yu-Hai** [akebe/address-parse#34]
感觉你的这个写的挺不错的，想参考这个写个java版的，但有些地方不是很懂，方便留个联系方式沟通下吗？谢谢🙏

**Comment by Yu-Hai** [comment]
我是搞Java的，index.js 里面的 parseName 函数的入参和作用没太看懂，问了几个前端也解释的不是很清楚，可以详细说一下吗

**Comment by akebe** [comment]
很抱歉比较少登邮箱现在才看到，其实原理就是用空格切分已经被抽取了省市区之后的字符串，得到最短的那一串字符，把他当成姓名而已
maxLen 是用来指定这个字符串的最大占位长度，默认值是11，因为超过5个汉字或11个英文的短词是名字的可能性就不高了
还有1个firstName是用未抽取省市区之前的用同一个函数取得的最短字符串，2次都命中它是名字的可能性更高



在 2021-03-09 13:59:57，"Yu-Hai" ***@***.***> 写道：

我是搞Java的，index.js 里面的 parseName 函数的入参和作用没太看懂，问了几个前端也解释的不是很清楚，可以详细说一下吗
