### ISSUE TITLE
直辖市详细地址带地区名 且和 省重复

### ISSUE THREAD

**Issue by lj1026203182** [akebe/address-parse#35]
如果 直辖市 详细地址出现和省市同样的名字  比如重庆市永川区南大街街道重庆文理学院  或者 北京市海淀区某个地方北京的大学 ,

**Comment by akebe** [comment]
感谢反馈，在`1.2.11`对解析结果的可信度参考值进行了细微调整，在启用`parseAll`的情况下，已经能得到正确的结果了
