### ISSUE TITLE
麻烦添加一下参考链接

### ISSUE THREAD

**Issue by pupuk** [akebe/address-parse#4]
你好，我是收货地址智能解析
https://github.com/pupuk/address-smart-parse 的作者
我在看您js的代码的时候，发现有些地方参考了我的代码
谢谢你觉得我的代码还不错
麻烦你在你项目的readme中，添加一下我的项目参考链接
后续我也会这个小项目持续改进
还望你能够理解

**Comment by akebe** [comment]
很久没有注意这个项目，很抱歉现在才回复，当时写的时候的搜不到现成的js库，自己实现时确参考了您的php项目，但是这个实现方式有缺陷，地区必须携带后缀才能被识别，后来使用中已经逻辑重构了，感谢您的分享

**Comment by pupuk** [comment]
> 很久没有注意这个项目，很抱歉现在才回复，当时写的时候的搜不到现成的js库，自己实现时确参考了您的php项目，但是这个实现方式有缺陷，地区必须携带后缀才能被识别，后来使用中已经逻辑重构了，感谢您的分享

谢谢，我也准备优化一下的PHP版本，欢迎共同学习；

**Comment by ldwonday** [comment]
哈哈，我也来凑下热闹，[https://github.com/ldwonday/zh-address-parse](https://github.com/ldwonday/zh-address-parse)这个也是我自己实现的，大家一起进步！~
