### ISSUE TITLE
反参

### ISSUE THREAD

**Issue by cHeartBeat** [akebe/address-parse#41]
可以在封装一下， 在返回地址信息的时候，将对应的省市区 code都进行返回吗？目前只有一个区code

**Comment by akebe** [comment]
这个没有必要，因为我们地址code的规范很简单`[省2位][市2位][区2位]`;
以福建省/福州市/福清市的code`350181`举例，`350100`是福州的编码，`350000`是福建的编码
用代码处理也就是`code.substr(0, 2) + '0000'`和`code.substr(0, 4) + '00'`，相当方便，把省市区编码都传出来完全没必要
