### ISSUE TITLE
地址解析错误

### ISSUE THREAD

**Issue by royfee** [akebe/address-parse#42]
下面这样的地址，解析的时候就会有错误
廣東省東莞市虎門鎮運河北路84號行運茶餐廳

解析后是这样的
{
  "province": "天津",
  "city": "天津市",
  "area": "河北区",
  "details": "路84號行運茶餐廳",
  "name": "廣東省東莞市虎門鎮運",
  "code": "120105",
  "__type": "parseByArea",
  "__parse": 0,
  "mobile": "",
  "zip_code": "",
  "phone": ""
}

**Comment by akebe** [comment]
因为这个库是使用地区树解析，现在是简体地区词库，所以识别不了繁体字哦，这个目前无解
