### ISSUE TITLE
江西上饶市广信区华坛山镇 识别不到 “广信区”

### ISSUE THREAD

**Issue by sanwv** [akebe/address-parse#44]
`江西上饶市广信区华坛山镇` 识别不到“广信区”

**Comment by sanwv** [comment]
* `重庆石柱县南宾街道` 识别不到“石柱土家族自治县”
* `重庆彭水县保家镇` 识别不到“彭水苗族土家族自治县”
* `重庆酉阳县钟多街道` 识别不到“酉阳土家族苗族自治县”
* `重庆秀山县清溪场镇` 识别不到“秀山土家族苗族自治县”

**Comment by akebe** [comment]
感谢反馈，已在`v1.2.17`版本修复
