### ISSUE TITLE
河北省邢台市信都区等地址整理

### ISSUE THREAD

**Issue by sanwv** [akebe/address-parse#47]
`河北省邢台市襄都区`  识别不到区（130502，襄都区）
`河北省邢台市信都区`  识别不到区
`河北省邢台市任泽区` 识别不到区
`黑龙江省伊春市伊美区`  识别不到区
`黑龙江省伊春市乌翠区` 识别不到区
`黑龙江省伊春市汤旺县` 识别不到区
`黑龙江省伊春市丰林县` 识别不到区
`黑龙江省伊春市大箐山县` 识别不到区
`黑龙江省伊春市金林区` 识别不到区

**Comment by sanwv** [comment]
`吉林省长春市公主岭市` 识别不到区
`浙江省温州市龙港市` 识别不到区
`江西省南昌市红谷滩区` 识别不到区

**Comment by akebe** [comment]
是因为地区库没有更新引起的，已经修复
