### ISSUE TITLE
no parseAll 解析详细地址有误，望解答！

### ISSUE THREAD

**Issue by itolskspv** [akebe/address-parse#48]
如：湖南省邵阳县长乐乡xxxxx
结果：
{
  "province": "湖南省",
  "city": "邵阳市",
  "area": "",
  "details": "县长乐乡xxxxx",
  "name": "",
  "code": "430500",
  "__type": "parseByProvince",
  "__parse": true,
  "mobile": "",
  "zip_code": "",
  "phone": ""
}

**Comment by akebe** [comment]
因为内部的解析顺序是优先通过`parseByProvince`省市区三级匹配，这是最快的。
为了能实现模糊匹配，在解析中是把区域后缀去掉再进行解析的，`邵阳县|邵阳市===邵阳`
这就导致了第三级与第二级地区名字一致的情况下，就比如你提供的例子`湖南省邵阳市邵阳县`，如果没有补齐会导致第三级地区`邵阳县`被识别为第二级地区`邵阳市`的情况，因为能匹配到省跟市，函数即判断为匹配成功，不会执行后续的解析了，这种情况目前只能通过parseAll强制执行逆解析`parseByArea`，来得到正确的结果
