### ISSUE TITLE
部分地区解析失败

### ISSUE THREAD

**Issue by leosteven2018** [akebe/address-parse#52]
如山西省大同市城区/矿区/南郊区/大同县。解析完后只有province和city， area为空。其他的省份不清楚

**Comment by akebe** [comment]
你好，查到大同市城区、南郊区、矿区2018年已撤销并到平城区、云冈区，目前解析采用的行政区划已经不包含这些地区数据了
http://www.mca.gov.cn/article/sj/xzqh/2020/20201201.html
