### ISSUE TITLE
在微信小程序的云函数环境下使用报错

### ISSUE THREAD

**Issue by shanezzz** [akebe/address-parse#6]
提示：AddressParse.parse is not a function
作者方便的话可以找朋友用微信小程序云函数复现一下问题。

我把AddressParse打印出来是如下内容：

 { ParseAddress: 

   { [Function: ParseAddress]

     ExcludeKeys: 

      [ '发件人',

        '收货地址',

        '收货人',

        '收件人',

        '收货',

        '手机号码',

        '邮编',

        '电话',

        '所在地区',

        '详细地址',

        '地址',

        '：',

        ':',

        '；',

        ';',

        '，',

        ',',

        '。',

        '、' ],

     ParseArea: ParseArea {},

     Reg: 

      { mobile: /(86-[1][0-9]{10})|(86[1][0-9]{10})|([1][0-9]{10})/g,

        phone: /(([0-9]{3,4}-)[0-9]{7,8})|([0-9]{12})|([0-9]{11})|([0-9]{10})|([0-9]{9})|([0-9]{8})|([0-9]{7})/g,

        zipCode: /([0-9]{6})/g } },

  AREA: 

   { district_list: 

      [ [Object],

        [Object],

        [Object],

        [Object],

        [Object],

        [Object],

        [Object],

        [Object] ],

     province_list: 

      { '110000': '北京',

        '120000': '天津',

        '130000': '河北省',

        '140000': '山西省',

        '150000': '内蒙古自治区',

        '210000': '辽宁省',

        '220000': '吉林省',

        '230000': '黑龙江省',

        '310000': '上海',

        '320000': '江苏省',

        '330000': '浙江省',

        '340000': '安徽省',

        '350000': '福建省',

        '360000': '江西省',

        '370000': '山东省',

        '410000': '河南省',

        '420000': '湖北省',

        '430000': '湖南省',

        '440000': '广东省',

        '450000': '广西壮族自治区',

        '460000': '海南省',

        '500000': '重庆',

        '510000': '四川省',

        '520000': '贵州省',

        '530000': '云南省',

        '540000': '西藏自治区',

        '610000': '陕西省',

        '620000': '甘肃省',

        '630000': '青海省',

        '640000': '宁夏回族自治区',

        '650000': '新疆维吾尔自治区',

        '710000': '台湾省',

        '810000': '香港特别行政区',

        '820000': '澳门特别行政区' },

     city_list: 

      { '太长，已手动省略...' },

     area_list: 

      { '太长，已手动省略...' },

  Utils: 

   { strLen: [Function: strLen],

     getAreaByCode: [Function: getAreaByCode],

     getAreaByAddress: [Function: getAreaByAddress],

     getTargetAreaListByCode: [Function: getTargetAreaListByCode],

     Reg: 

      { mobile: /(86-[1][0-9]{10})|(86[1][0-9]{10})|([1][0-9]{10})/g,

        phone: /(([0-9]{3,4}-)[0-9]{7,8})|([0-9]{12})|([0-9]{11})|([0-9]{10})|([0-9]{9})|([0-9]{8})|([0-9]{7})/g,

        zipCode: /([0-9]{6})/g } },

  default: ParseAddress {} }

**Comment by shanezzz** [comment]
我的微信是18657161339，如有需要请添加

**Comment by shanezzz** [comment]
我又调试了一下，使用以下两种方式可以调用成功：
new AddressParse.ParseAddress().parse('福建省福州市福清市石竹街道义明综合楼3F，15000000000，asseek')
或者
AddressParse.default.parse('福建省福州市福清市石竹街道义明综合楼3F，15000000000，asseek')

**Comment by akebe** [comment]
示例中是直接使用es6模块化语法调用，如果是用`require`载入模块的确是有差异的
````
import AddressParse, {AREA, Utils} from 'address-parse';
````
等同于
````
const AddressParse = require('address-parse').default;

const {AREA, Utils} = require('address-parse');
````
