### ISSUE TITLE
parseByProvince这个匹配省份方法有点懵

### ISSUE THREAD

**Issue by bigAken** [akebe/address-parse#7]
parse-area.js文件中121行
` let shortProvince = index > -1 ? '' : ParseArea.ProvinceShort[code];`
是不是应该写成这样的啊   @@查找到对应的省份应该返回对应的省份缩略名，源码中刚好相反
` let shortProvince = index > -1 ? ParseArea.ProvinceShort[code] :  '' ;`
@akebe

**Comment by akebe** [comment]
没有写错，这个`index`判定上一句的结果，也就是字符串内是否包含完整`province`
如果包含完整`province`就用不着`shortProvince`结果直接赋为空了 
简单解释下  `province` 是完整名，如`内蒙古自治区`，而 `shortProvince`是简名 如`内蒙古`，如果字符串命中了`内蒙古自治区`，就没必要对`内蒙古`这个字符串再做处理了。
`shortProvince`判定是为了处理经常出现的省市名简写导致无法解析的情况，比如“内蒙古包头”，如果没有 `shortProvince`就很难解析出"内蒙古自治区 / 包头市"了

**Comment by bigAken** [comment]
好 谢谢指点迷津 我再看下
