### ISSUE TITLE
你好东莞市区的地址是不是有问题 ？

### ISSUE THREAD

**Issue by zfn215** [akebe/address-parse#8]
镇的code是最新的吗 ？

**Comment by zfn215** [comment]
code: "442000002"
name: "东区街道" 他们对镇的查找和你给的code不同 请问可以解决下吗？

**Comment by zfn215** [comment]
基于iviewarea(2.0去做的回显) https://github.com/oyv1cent/iview-area-new

**Comment by akebe** [comment]
你好 项目中使用的`area`数据来源于vant的[area.js](https://github.com/youzan/vant/blob/dev/src/area/demo/area.js)，刚才追溯了一下他这个数据应该是来源自[中华人民共和国行政区划代码](http://www.mca.gov.cn/article/sj/xzqh/2019/)，这个数据源`441900 | 东莞市`,`442000 | 中山市`没有下级区划，猜测为规范为统一6位`code`他应该是采用了自定制编码，因为我这个项目目前也采用统一6位`code`规范，所以暂时无法兼容`code: "442000002"`这个的数据格式哦，不过解决方式也简单，你可以建个映射表统一处理下即可
````
const codes = {
  '442018': '442000002',
  ...,
};
const [result] = AddressParse.parse('广东省中山市东区街道');

if (codes[result.code]){
  result.code = codes[result.code];
} 
````
后面有时间我会抽空完善下这块

**Comment by zfn215** [comment]
谢谢你的及时回复 后期是通过映射的关系处理了一下 已经很完美



在 2019-11-11 21:37:38，"akebe" <notifications@github.com> 写道：

你好 项目中使用的area数据来源于vant的area.js，刚才追溯了一下他这个数据应该是来源自中华人民共和国行政区划代码，这个数据源441900 | 东莞市,442000 | 中山市没有下级区划，猜测为规范为统一6位code他应该是采用了自定制编码，因为我这个项目目前也采用统一6位code规范，所以暂时无法兼容code: "442000002"这个的数据格式哦，不过解决方式也简单，你可以建个映射表统一处理下即可

const codes = {
  '442018': '442000002',
  ...,
};
const [result] = AddressParse.parse('广东省中山市东区街道');

if (codes[result.code]){
  result.code = codes[result.code];
} 


后面有时间我会抽空完善下这块
