### ISSUE TITLE
你好 发现广东省东莞市和中山市的code不是最新的

### ISSUE THREAD

**Issue by zfn215** [akebe/address-parse#9]

**Comment by akebe** [comment]
这2个地区code跟[民政部2019年行政区划代码](http://www.mca.gov.cn/article/sj/xzqh/2019/2019/201912241458.html)是一致的哦，如果是指下辖区划的`code`参考下这个Issuse的解决方法是否能帮到你。https://github.com/akebe/address-parse/issues/8
